# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Wilka Carvalho
tagline:             'Aspiring Brain and Machine Learning Scientist'
description:         'A small website to introduce you to myself'
url:                 https://wcarvalho.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Wilka Carvalho
  url:               https://wcarvalho.github.io/
  email:             wcarvalho92@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]